#485540[C#テキスト]1章演習問題
teshima-being/TextC pull request #1
Opened 2024-04-15 08:37 UTC by teshima-being

1章の章末問題の解答です。

2024-04-18 09:32 UTC, k-miyahara-being requested changes
ほとんど気になる箇所はありませんでした！

コードのきれいさという点で、気になるところがあったため確認をお願いします。
ある箇所で指摘された内容は、他の箇所でも同じ指摘がないようにあわせて確認・修正をお願いします。

2024-04-18 09:32 UTC, k-miyahara-being commented on 章末問題1/Practice1-1-1/Product.cs
> +using System.Threading.Tasks;
不要なusingは削除してください。
Visual Studioでマウスホバーすると、↓のようなメッセージが出ると思うので、電球💡アイコンを押下すると削除するメニューが現れて自動で消してくれたりします。
![image](https://github.com/teshima-being/TextC/assets/86827185/e61fc923-c5d7-4a0d-963b-16bab25f30b8)

この電球アイコンがあるときはコードの改善を提案してくれているので、また機会があれば見てみてください

2024-04-18 09:32 UTC, k-miyahara-being commented on 章末問題1/Practice1-1-1/Product.cs
> +        public int Price { get; set; }
GetTaxメソッドにつけているように、プロパティやクラス、コンストラクタにも同様のコメントを書いてみてください。
[コーディング規約 > コメント](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88)

この書き方は[ドキュメントコメント](https://learn.microsoft.com/ja-jp/visualstudio/ide/reference/generate-xml-documentation-comments?view=vs-2022)といって、そのプロパティやメソッドをマウスホバーしたときに一緒にコメントが表示されるようになります。
クラス外からプロパティを使うときなどに、そのプロパティが定義されているクラスにわざわざ移動して確認する必要がなくなるため、非常に役立ちます。
![image](https://github.com/teshima-being/TextC/assets/86827185/021b504f-98e5-439f-8ba0-208f50437455)

プロパティやメソッドの1つ上の行で`///` (スラッシュ3つ)と入力することで自動で補完してくれるので、やってみてください。

2024-04-18 09:32 UTC, k-miyahara-being commented on 章末問題1/Practice1-1-3/Person.cs
> +            if (wToday < Birthday.AddYears(wAge))
[コーディング規約](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#using:~:text=%E3%82%8A%E3%81%9F%E3%81%84%E3%81%93%E3%81%A8%0A%E3%80%80%E3%80%80%E3%80%80%E3%80%80%7D%0A%E3%80%80%E3%80%80%E3%80%80%7D%0A%0A%E3%83%BB-,this,-%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3%EF%BC%9A%E3%82%AF%E3%83%A9%E3%82%B9%E5%86%85)にあるように、同一クラス内のプロパティやメソッドを参照する際は、`this`を付けることを意識してみてください。

2024-04-18 09:32 UTC, k-miyahara-being commented on 章末問題1/Practice1-1-3/Program.cs
> +            Console.WriteLine(wStudent.Birthday.ToString("yyyy/mm/dd"));
ここだけ 月 の表示がおかしいです。
以前日報に書いてくださっていたことですね！

2024-04-19 04:38 UTC, teshima-being commented on 章末問題1/Practice1-1-1/Product.cs
> +using System.Threading.Tasks;
各プログラムにて不要なusingを削除しました。

2024-04-19 04:43 UTC, teshima-being commented on 章末問題1/Practice1-1-1/Product.cs
> +        public int Price { get; set; }
各クラス、プロパティ、コンストラクタにもドキュメントコメントを設定しました。
クラス外から参照するときにドキュメントコメントの入力内容が確認できるのですね。
「ドキュメントコメントというものを付けることが推奨されているのか」とそこまで深く考えられていませんでしたが、「なぜ付けることが推奨されているのか」までちゃんと考えないとだめですね…。

2024-04-19 04:46 UTC, teshima-being commented on 章末問題1/Practice1-1-3/Program.cs
> +            Console.WriteLine(wStudent.Birthday.ToString("yyyy/mm/dd"));
日付の書式設定を修正しました。

2024-04-19 04:47 UTC, teshima-being commented on 章末問題1/Practice1-1-3/Person.cs
> +            if (wToday < Birthday.AddYears(wAge))
クラス内のプロパティを参照する際にthisを付けました。

2024-04-22 02:07 UTC, k-miyahara-being commented on 章末問題1/Practice1-1-1/Product.cs
> +        public int Price { get; set; }
コードは、書いた本人以外の第三者でも理解しやすいようになっていることが理想です。
Gaia Cloudのようにたくさんの人の手で日々更新されていくようなコードにとっては特に重要なことで、保守のしやすさに直結すると思っています。
ドキュメントコメントもそうですが、メソッドの中に書かれるようなコメントも第三者にとっては読み進める上で大きな助けになります。
ぜひ今後は、自分以外が読んで理解できるか？も意識して書いていっていただけると良いかなと思います！

2024-04-22 04:17 UTC, merged