#486281[C#テキスト]2章演習問題
teshima-being/TextC pull request #2
Opened 2024-04-16 08:41 UTC by teshima-being

2章の章末問題の解答です。

2024-04-18 10:47 UTC, ohdaira-being requested changes
数点指摘しましたが、とてもきれいなコードでした。
ある箇所で指摘された内容は、他の箇所でも同じ指摘がないようにあわせて確認・修正をお願いします。

2024-04-18 10:47 UTC, ohdaira-being commented on 章末問題2/Practice2-1-1/Song.cs
> +        public int Length { get; set; }
プロパティ・コンストラクタ・publicメソッドに関しては、/// で始まるXMLドキュメンテーションコメントで説明を入れるようにしてください。
以下の記事を読んで、コメントの修正をお願いいたします。
https://qiita.com/matsumoyu/items/5930cc7ffe2f4f4aafa2

2024-04-18 10:47 UTC, ohdaira-being commented on 章末問題2/Practice2-3/Program.cs
> +            SalesCounter wSales = new SalesCounter(@"..\..\sales.txt");
右辺から型が明らかな場合は、varで省略した方が読みやすいです。
暗黙的な型宣言（var）に修正をお願いします。

2024-04-18 10:47 UTC, ohdaira-being commented on 章末問題2/Practice2-3/Program.cs
> +            IDictionary<string, int> wAmountPerStore = wSales.GetPerStoreSales();
`wAmountPerStore `について
この変数は、**複数の**店舗の情報を格納したものですが、この変数名を見ると単数形で分かりづらいです。
複数のものを意味する変数は、名前から複数だということが分かるようにしてください。

2024-04-18 10:47 UTC, ohdaira-being commented on 章末問題2/Practice2-3/SalesCounter.cs
> +            foreach (string wLine in wLines) {
foreach(単数in複数)
初めからこのように書けるのはすごいです！
foreachは、良く使いますので、この感覚忘れないようにお願いします！

2024-04-19 05:31 UTC, teshima-being commented on 章末問題2/Practice2-1-1/Song.cs
> +        public int Length { get; set; }
各クラス、プロパティ、コンストラクタ、メソッドにドキュメントコメントを追加しました。
ドキュメントコメントの記述の仕方によってはVisualStudio内でのリンクを設定することもできるんですね。

2024-04-19 05:31 UTC, teshima-being commented on 章末問題2/Practice2-3/Program.cs
> +            SalesCounter wSales = new SalesCounter(@"..\..\sales.txt");
右辺から型が明らかな場合について、varを利用するように変更しました。

2024-04-19 05:32 UTC, teshima-being commented on 章末問題2/Practice2-3/Program.cs
> +            IDictionary<string, int> wAmountPerStore = wSales.GetPerStoreSales();
複数情報をもつ変数について、変数名を単数形から複数形に変更しました。

2024-04-24 01:15 UTC, merged