#486282[C#テキスト]3章演習問題
teshima-being/TextC pull request #3
Opened 2024-04-18 06:59 UTC by teshima-being

3章の章末問題の解答です。

2024-04-23 12:13 UTC, ohdaira-being requested changes
とてもきれいなコードでした。
数点指摘しましたので、修正をお願いします。

2024-04-23 12:13 UTC, odaira1119 commented on 章末問題3/Practice3-1-1/Program.cs
> +            bool ExistsNum = wNumbers.Exists(n => n % 8 == 0 || n % 9 == 0);
コーディング規約のため、wを付けるようにしてください。
変数名については、Existsが複数形で少し違和感を感じましたので、変数名についても考え直してみてください。
補足：bool型の変数名には、Is・Has・Canあたりが良く使われます

2024-04-23 12:13 UTC, odaira1119 commented on 章末問題3/Practice3-1-2/Program.cs
> +            wNumbers.ForEach(n => Console.WriteLine(n / C_Number));
コーディング規約では、リンク内でxyzを使うようになっています。
なので、nをxに修正お願いします。

2024-04-23 12:13 UTC, odaira1119 commented on 章末問題3/Practice3-1-3/Program.cs
> +            var wResult = new StringBuilder("");
空の文字列を`""`でも表せますが、可読性の面で`string.Empty`の方が推奨されています。
こちらも修正しておきましょう。

2024-04-23 12:13 UTC, odaira1119 commented on 章末問題3/Practice3-1-4/Program.cs
> +            List<int> wNewNumbers = wNumbers.Select(n => n * 2).ToList();
右辺でToList()しているため、型が明らかになっています。
また、nではなくxに修正をお願いします。

2024-04-23 12:13 UTC, odaira1119 commented on 章末問題3/Practice3-2-1/Program.cs
> +            } while (true);
実は、`do-while ループ`は可読性などの面で基本的に使われないです。
whileまたはその他のループ構文を使って書き換えてみてほしいです。

2024-04-24 00:44 UTC, teshima-being commented on 章末問題3/Practice3-1-2/Program.cs
> +            wNumbers.ForEach(n => Console.WriteLine(n / C_Number));
LINQで使用するパラメータの文字を変更しました。

2024-04-24 00:45 UTC, teshima-being commented on 章末問題3/Practice3-1-3/Program.cs
> +            var wResult = new StringBuilder("");
空文字の表現を""からstring.Emptyに修正しました。

2024-04-24 00:51 UTC, teshima-being commented on 章末問題3/Practice3-1-4/Program.cs
> +            List<int> wNewNumbers = wNumbers.Select(n => n * 2).ToList();
再度確認したところ、そもそもListである必要性がなかったため、ToList()を削除しIEnumerableインターフェースに変更しました。

2024-04-24 00:56 UTC, teshima-being commented on 章末問題3/Practice3-2-1/Program.cs
> +            } while (true);
do-while文ではなく、while文に修正いたしました。

2024-04-24 01:04 UTC, teshima-being commented on 章末問題3/Practice3-1-1/Program.cs
> +            bool ExistsNum = wNumbers.Exists(n => n % 8 == 0 || n % 9 == 0);
変数名ExistsNumをwHasNumberに変更しました。

2024-04-25 09:06 UTC, ohdaira-being requested changes
1点指摘しています。
ご確認ください。

2024-04-25 09:06 UTC, ohdaira-being commented on 章末問題3/Practice3-2-4/Program.cs
> +            var wCityNames = vList.Where(x => x[0] == vChar).ToList();
`vList`と`vChar`の名前から何を表すのか分かりづらいです。
命名を考え直してみてください。
補足：`List`型の変数に`○○List`といったような、型名を変数名に付けるときは、だいたい不適切な名前かと思います。

+α（修正任意）
引数の型`List<string>`について、少し考えてみてほしいです。
以下の記事を読んでみてください。
https://qiita.com/hysui/items/a93987905c1d2a2f51bb

2024-04-26 02:15 UTC, teshima-being commented on 章末問題3/Practice3-2-4/Program.cs
> +            var wCityNames = vList.Where(x => x[0] == vChar).ToList();
①変数の命名を一部変更しました。
vList → vCityNames
vChar → vKeyWord
wCityNames → wCityNamesStartWithKey （※）

※部について、「名称がキーワードで始まる都市名だけを抽出したもの」を表したい場合、
多少名前が長くなろうとも、何を格納しているのかがより分かりやすいほうが良いという
ことでよいでしょうか。

②List固有の処理を内部に含まないメソッドについて、引数の型を変更しました。
List<string> → IEnumerable<string>

2024-05-08 02:40 UTC, merged